# this is single soucce of the truth for my application's settings
# as its not .java by changing this there will be no need for the recompilation
 
watch.path=/home/gauravpatil/Documents/SYNC/test-repo 
idle.time=300
auto.commit=true
auto.push=true
git.branch=main
log.level=INFO
